"""Team / Unit View: how PIS moves by formation, coverage, down, PA, etc."""
from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

from app.lib import data, ui

st.set_page_config(page_title="Team / Unit View", page_icon="🏟️", layout="wide")
ui.inject_theme()
st.title("🏟️ Team / Unit View")

if not data.cache_exists():
    ui.cache_warning()
    st.stop()

plays = data.load_plays()
games = data.load_games()
pp = data.load_player_play()

df = plays[plays.scorable].merge(games[["gameId", "week"]], on="gameId",
                                 how="left", suffixes=("", "_g"))

# pressures allowed per play for context
pa = (pp[pp.side == "offense"].groupby(["gameId", "playId"])
      .pressureAllowed.sum().rename("press_allowed").reset_index())
df = df.merge(pa, on=["gameId", "playId"], how="left").fillna({"press_allowed": 0})

PX_DARK = dict(paper_bgcolor="#0b1220", plot_bgcolor="#0b1220",
               font_color="#e5e7eb")

tab1, tab2, tab3 = st.tabs(["Offensive lines", "Defensive fronts",
                            "Situational splits"])

# ---------------------------------------------------------------------------
# OFFENSE: team pass-protection ranking
# ---------------------------------------------------------------------------
with tab1:
    st.subheader("Offensive-line pass protection, by team")
    o = (df.groupby("possessionTeam")
         .agg(plays=("playId", "size"), avg_pis=("pis", "mean"),
              pressure_rate=("press_allowed", lambda s: (s > 0).mean()),
              sack_rate=("passResult", lambda s: (s == "S").mean()))
         .reset_index().sort_values("avg_pis", ascending=False))
    o["avg_pis"] = o["avg_pis"].round(1)
    o["pressure_rate"] = (o["pressure_rate"] * 100).round(1)
    o["sack_rate"] = (o["sack_rate"] * 100).round(1)

    fig = px.bar(o, x="avg_pis", y="possessionTeam", orientation="h",
                 color="avg_pis", color_continuous_scale="RdYlGn",
                 labels={"avg_pis": "Avg PIS", "possessionTeam": ""},
                 height=640)
    fig.update_layout(**PX_DARK, yaxis=dict(autorange="reversed"),
                      coloraxis_showscale=False, margin=dict(l=4, r=4, t=10, b=4))
    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

    best = o.iloc[0]; worst = o.iloc[-1]
    st.markdown(
        f"💡 **{best.possessionTeam}** built the cleanest pockets "
        f"(avg PIS {best.avg_pis}, pressure allowed {best.pressure_rate}% of "
        f"dropbacks), while **{worst.possessionTeam}** struggled most "
        f"(avg PIS {worst.avg_pis}, {worst.pressure_rate}%).")
    st.dataframe(o.rename(columns={"possessionTeam": "Team", "plays": "Plays",
                 "avg_pis": "Avg PIS", "pressure_rate": "Press%",
                 "sack_rate": "Sack%"}), use_container_width=True, hide_index=True)

# ---------------------------------------------------------------------------
# DEFENSE: pressure generated by team
# ---------------------------------------------------------------------------
with tab2:
    st.subheader("Defensive front pressure, by team (lower pocket PIS = better rush)")
    d = (df.groupby("defensiveTeam")
         .agg(plays=("playId", "size"), avg_pis_allowed=("pis", "mean"),
              pressure_rate=("press_allowed", lambda s: (s > 0).mean()),
              sack_rate=("passResult", lambda s: (s == "S").mean()))
         .reset_index().sort_values("avg_pis_allowed"))
    d["avg_pis_allowed"] = d["avg_pis_allowed"].round(1)
    d["pressure_rate"] = (d["pressure_rate"] * 100).round(1)
    d["sack_rate"] = (d["sack_rate"] * 100).round(1)

    fig = px.bar(d, x="avg_pis_allowed", y="defensiveTeam", orientation="h",
                 color="avg_pis_allowed", color_continuous_scale="RdYlGn",
                 labels={"avg_pis_allowed": "Avg pocket PIS allowed",
                         "defensiveTeam": ""}, height=640)
    fig.update_layout(**PX_DARK, yaxis=dict(autorange="reversed"),
                      coloraxis_showscale=False, margin=dict(l=4, r=4, t=10, b=4))
    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

    best = d.iloc[0]
    st.markdown(
        f"💡 **{best.defensiveTeam}** disrupted pockets most (opponents' avg PIS "
        f"only {best.avg_pis_allowed}, pressure on {best.pressure_rate}% of "
        f"dropbacks).")
    st.dataframe(d.rename(columns={"defensiveTeam": "Team", "plays": "Plays",
                 "avg_pis_allowed": "Avg PIS allowed", "pressure_rate": "Press%",
                 "sack_rate": "Sack%"}), use_container_width=True, hide_index=True)

# ---------------------------------------------------------------------------
# SITUATIONAL
# ---------------------------------------------------------------------------
with tab3:
    st.subheader("How pocket integrity shifts by situation")
    dim = st.selectbox("Split by", {
        "offenseFormation": "Formation",
        "pff_passCoverage": "Coverage",
        "dropBackType": "Dropback type",
        "down": "Down",
        "pff_playAction": "Play action",
    }.keys(), format_func=lambda k: {
        "offenseFormation": "Formation", "pff_passCoverage": "Coverage",
        "dropBackType": "Dropback type", "down": "Down",
        "pff_playAction": "Play action"}[k])

    g = (df.dropna(subset=[dim]).groupby(dim)
         .agg(plays=("playId", "size"), avg_pis=("pis", "mean"),
              pressure_rate=("press_allowed", lambda s: (s > 0).mean()))
         .reset_index())
    g = g[g.plays >= 20].sort_values("avg_pis", ascending=False)
    g["avg_pis"] = g["avg_pis"].round(1)
    g["pressure_rate"] = (g["pressure_rate"] * 100).round(1)
    g[dim] = g[dim].astype(str)

    fig = px.bar(g, x=dim, y="avg_pis", color="avg_pis",
                 color_continuous_scale="RdYlGn",
                 text="avg_pis", labels={"avg_pis": "Avg PIS"}, height=420)
    fig.update_layout(**PX_DARK, coloraxis_showscale=False,
                      margin=dict(l=4, r=4, t=10, b=4), yaxis=dict(range=[0, 100]))
    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})
    st.dataframe(g.rename(columns={dim: "Split", "plays": "Plays",
                 "avg_pis": "Avg PIS", "pressure_rate": "Press%"}),
                 use_container_width=True, hide_index=True)

    # a couple of plain insights
    if len(g) >= 2:
        hi, lo = g.iloc[0], g.iloc[-1]
        st.markdown(
            f"💡 Pockets held best on **{hi[dim]}** (PIS {hi.avg_pis}) and worst "
            f"on **{lo[dim]}** (PIS {lo.avg_pis}) — a {hi.avg_pis - lo.avg_pis:.0f} "
            "point gap.")
